### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by AndreaLoden** [nexxtv/nexxPLAY-android#1]
Hi, is it possible to give the library a list of IDs and let it play them as playlist without leaving the player? I see that there is a `public enum PlayMode` with a `playlist` value, but how can I give the player the IDs? Thanks

**Comment by mfentross** [comment]
Hi, there is a PlayMode called itemlist. With that you can give multiple media ids as a parameter separated with a comma.

**Comment by AndreaLoden** [comment]
Hi @mfentross  thanks for the quick response.

I tried with your advice and the videos in the playlist are in fact played but the information shown in the leanback controls stay the same as the first video, only the duration is updated.
