### ISSUE TITLE
Small bugs 

### ISSUE THREAD

**Issue by NetPumi2** [nexxtv/nexxPLAY-android#12]
Hi, we finally update nexx to the latest version and it works fine.
I just want to notify some small things what would be nice to have
1) subtitles menu => if I want to change subtitles the menu is in middle of the screen and when I tap on a button I always pause the video. And the style is ugly :D 
![screenshot_20180815-100159_buntede](https://user-images.githubusercontent.com/5843275/44139493-8fa29e1e-a077-11e8-82ea-740cb0683abe.jpg)

2) Is there some way how to remove/disable the fullscreen button?  We don't use it on android (video is always full screen)
![screen shot 2018-08-15 at 10 40 50](https://user-images.githubusercontent.com/5843275/44139560-b3b8eeb6-a077-11e8-9156-6f5acc24a143.png)

THX 🗡

**Comment by boredom2** [comment]
Hi there, please dont release this Version :)
The Display of the Caption Choose is definitely not correct. We will provide a Fix asap.
Thanks for notifying us.
Concerning the Fullscreen Behaviour - thats a common Question for Customers, who only include the "Fullscreen" Version of the Player and dont embed it in the View Models. Malte will answer that one too asap :)

**Comment by mfentross** [comment]
Hi @NetPumi2 , unfortunately I cannot reproduce the first issue. Could you please give me more information how you run into this issue (device, video id, domain id)? For the issue with the fullscreen button we have the function enableCordova(). For convenience I added the function setAlwaysFullscreen().

**Comment by fdobre** [comment]
@boredom2  and @mfentross is 3.2.1 production ready?
Thank you for the fast response!

We are making a release candidate today.
What version do you recommend releasing? What is the latest stable one?
We couldn't make 3.0.5 (last tag from here) work but 3.1.2 seems to be stable.

Can we find somewhere a change.log for 3.2.x?

We need your advice.

**Comment by boredom2** [comment]
We have currently a lot of Releases (also without Release Noted)due to many new Functionalities (which are not currently relevant for you though). The Situation will normalize again soon, dont worry :)
The latest Version ist 3.2.1 and the Changes are absolutely minimal and client-specific, there is no Problem in always using the latest Version.

**Comment by NetPumi2** [comment]
so we updated nexx to 3.2.1 ...

**Comment by boredom2** [comment]
and... is it working? :-)

**Comment by NetPumi2** [comment]
it works from my point of view ... our testers will test it today if something happens I will let you know
