### ISSUE TITLE
Codec issues on API level 22

### ISSUE THREAD

**Issue by stigi** [nexxtv/nexxPLAY-android#13]
Hi,

I've tested our app against API level 22 and none of our videos are playing and the player shows:
> Das Video wurde nicht gefunden

The same videos play on API level 25 (all tested in emulator).

From the logs I believe it might be a codec issue.

<details>
 <summary>`adb logcat` output</summary>
I/ActivityManager( 1486): START u0 {flg=0x10000000 cmp=net.funk.tv.debug/net.funk.tv.player.PlayerActivity (has extras)} from uid 10038 on display 0
V/WindowManager( 1486): addAppToken: AppWindowToken{21b6d990 token=Token{3c62ac53 ActivityRecord{1590d442 u0 net.funk.tv.debug/net.funk.tv.player.PlayerActivity t2}}} to stack=0 task=2 at 1
D/PlayerActivity( 2387): Started player for video : 133618
W/ResourcesManager( 2387): Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
W/System.err( 2387): com.google.android.gms.common.GooglePlayServicesNotAvailableException
W/System.err( 2387): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source)
W/System.err( 2387): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source)
W/System.err( 2387): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source)
W/System.err( 2387): 	at tv.nexx.android.player.ads.GetAdIDAsyncTask.doInBackground(GetAdIDAsyncTask.java:28)
W/System.err( 2387): 	at tv.nexx.android.player.ads.GetAdIDAsyncTask.doInBackground(GetAdIDAsyncTask.java:16)
W/System.err( 2387): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/System.err( 2387): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err( 2387): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err( 2387): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 2387): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 2387): 	at java.lang.Thread.run(Thread.java:818)
I/MediaFocusControl( 1486):  AudioFocus  requestAudioFocus() from android.media.AudioManager@25bcf826tv.nexx.android.player.NexxPlayerAndroidImpl$4@38756c67 req=1flags=0x0
D/NEXX    ( 2387): Calling startPlay(cid=null, client=741, playmode=single, param=133618, startpos=0, startitem=0
I/NEXX    ( 2387): release
D/InitFlash( 2387): submit
D/InitFlashAsyncTask( 2387): Constructor
D/NEXX    ( 2387): NexxPlayerAndroid::onActivityResume
V/WindowManager( 1486): Adding window Window{33dbf28e u0 net.funk.tv.debug/net.funk.tv.player.PlayerActivity} at 3 of 4 (after Window{33735181 u0 net.funk.tv.debug/net.funk.tv.MainActivity})
V/WindowManager( 1486): Adding window Window{2d7febc u0 SurfaceView} at 3 of 5 (before Window{33dbf28e u0 net.funk.tv.debug/net.funk.tv.player.PlayerActivity})
V/WindowManager( 1486): Adding window Window{18a8a99a u0 SurfaceView} at 3 of 6 (before Window{2d7febc u0 SurfaceView})
D/AudioManager( 2387): AudioManager dispatching onAudioFocusChange(-1) for android.media.AudioManager@197b6d9btv.nexx.android.player.NexxPlayerAndroidImpl$4@15d51538
I/ActivityManager( 1486): Displayed net.funk.tv.debug/net.funk.tv.player.PlayerActivity: +106ms
D/APIManager( 2387): Received client token: N741XHKTQAPQCSPNAFFWK
D/InitFlashAsyncTask( 2387): ---there--- 140
D/SerialReqAsyncTask( 2387): response code: 201
I/NEXX    ( 2387): got client data, play mode is single
D/NEXX    ( 2387): player skin: minimalwithtime
D/NEXX-UI ( 2387): setLayout 2130968694
D/NEXX-UI ( 2387): initControllerView
I/NEXX    ( 2387): got media data, 1 items
D/SerialReqAsyncTask( 2387): response code: 201
I/NEXX    ( 2387): got exit play data, 10 items
D/NEXX    ( 2387): exit play media list available, size 10
D/SerialReqAsyncTask( 2387): response code: 201
E/NEXX    ( 2387): no media list
I/NEXX    ( 2387): release
D/NEXX    ( 2387): playing media https://funk-01.akamaized.net/c3583d1f-a2ef-4c71-ba17-77d0b144fa80/133618_src.ism/Manifest(format=mpd-time-csf)
I/NEXX    ( 2387): prepare https://funk-01.akamaized.net/c3583d1f-a2ef-4c71-ba17-77d0b144fa80/133618_src.ism/Manifest(format=mpd-time-csf), start position 0
I/ExoPlayerImpl( 2387): Init 17da4922 [ExoPlayerLib/2.8.1] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/EventLogger( 2387): seekStarted [0.00, 0.00, window=0]
D/EventLogger( 2387): positionDiscontinuity [0.00, 0.00, window=0, SEEK]
W/MediaSessionCompat( 2387): Couldn't find a unique registered media button receiver in the given context.
D/EventLogger( 2387): start [0]
D/EventLogger( 2387): state [0.01, 0.00, window=0, false, BUFFERING]
D/ExoPlayerAdapter( 2387): State is buffering
D/NEXX    ( 2387): exoplayer state changed 2
D/NEXX-UI ( 2387): show, timeout 3000
D/NEXX    ( 2387): player state BUFFERING
D/NEXX    ( 2387): Loading->Loading
D/NEXX    ( 2387): Loading
D/NEXX    ( 2387): UI Loading
I/NEXX    ( 2387): play
D/EventLogger( 2387): state [0.02, 0.00, window=0, true, BUFFERING]
D/ExoPlayerAdapter( 2387): State is buffering
D/EventLogger( 2387): state [0.02, 0.00, window=0, false, BUFFERING]
D/ExoPlayerAdapter( 2387): State is buffering
D/EventLogger( 2387): positionDiscontinuity [0.02, 0.00, window=0, SEEK]
D/EventLogger( 2387): state [0.02, 0.00, window=0, true, BUFFERING]
D/ExoPlayerAdapter( 2387): State is buffering
D/EventLogger( 2387): timelineChanged [0.03, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
D/EventLogger( 2387):   period [312.21]
D/EventLogger( 2387):   window [312.16, true, false]
D/EventLogger( 2387): ]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.640028, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.640028, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001F, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001F, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64000D, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.640028, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.640028, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/EventLogger( 2387): seekProcessed [0.03, 0.00, window=0]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001F, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001F, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64000D, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/EventLogger( 2387): mediaPeriodCreated [0.04, 0.00, window=0, period=0]
D/EventLogger( 2387): loading [0.04, 0.00, window=0, period=0, true]
D/EventLogger( 2387): decoderEnabled [0.04, 0.00, window=0, period=0, video]
D/EventLogger( 2387): decoderEnabled [0.04, 0.00, window=0, period=0, audio]
D/EventLogger( 2387): tracksChanged [0.04, 0.00, window=0, period=0,
D/EventLogger( 2387):   Renderer:0 [
D/EventLogger( 2387):     Group:0, adaptive_supported=YES [
D/EventLogger( 2387):       [ ] Track:0, id=1_V_video_1, mimeType=video/avc, bitrate=5597728, res=1920x1080, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [ ] Track:1, id=1_V_video_2, mimeType=video/avc, bitrate=3720874, res=1920x1080, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [ ] Track:2, id=1_V_video_3, mimeType=video/avc, bitrate=2320375, res=1280x720, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [ ] Track:3, id=1_V_video_4, mimeType=video/avc, bitrate=1397555, res=960x540, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [ ] Track:4, id=1_V_video_5, mimeType=video/avc, bitrate=838895, res=720x404, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [ ] Track:5, id=1_V_video_6, mimeType=video/avc, bitrate=607509, res=640x360, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [X] Track:6, id=1_V_video_7, mimeType=video/avc, bitrate=372726, res=320x180, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):     ]
D/EventLogger( 2387):   ]
D/EventLogger( 2387):   Renderer:1 [
D/EventLogger( 2387):     Group:0, adaptive_supported=N/A [
D/EventLogger( 2387):       [X] Track:0, id=5_A_aac_UND_2_127_1, mimeType=audio/mp4a-latm, bitrate=127999, sample_rate=48000, supported=YES
D/EventLogger( 2387):     ]
D/EventLogger( 2387):   ]
D/EventLogger( 2387): ]
D/ExoPlayerAdapter( 2387): onTracksChanged
D/EventLogger( 2387): mediaPeriodReadingStarted [0.05, 0.00, window=0, period=0]
I/OMXClient( 2387): Using client-side OMX mux.
W/OMXNodeInstance( 2387): [1:google.h264.decoder] component does not support metadata mode; using fallback
E/ACodec  ( 2387): [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
D/EventLogger( 2387): decoderInitialized [0.08, 0.00, window=0, period=0, video, OMX.google.h264.decoder]
D/EventLogger( 2387): decoderInputFormatChanged [0.08, 0.00, window=0, period=0, video, id=1_V_video_7, mimeType=video/avc, bitrate=372726, res=320x180]
E/SoftAVC ( 2387): Decoder failed: -2
E/ACodec  ( 2387): [OMX.google.h264.decoder] ERROR(0x80001001)
D/EventLogger( 2387): downstreamFormatChanged [0.09, 0.00, window=0, period=0, id=1_V_video_7, mimeType=video/avc, bitrate=372726, res=320x180]
E/ACodec  ( 2387): signalError(omxError 0x80001001, internalError -2147483648)
E/MediaCodec( 2387): Codec reported err 0x80001001, actionCode 0, while in state 6
E/ExoPlayerImplInternal( 2387): Internal runtime error.
E/ExoPlayerImplInternal( 2387): java.lang.IllegalStateException
E/ExoPlayerImplInternal( 2387): 	at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
E/ExoPlayerImplInternal( 2387): 	at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:637)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
E/ExoPlayerImplInternal( 2387): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2387): 	at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal( 2387): 	at android.os.HandlerThread.run(HandlerThread.java:61)
D/EventLogger( 2387): decoderDisabled [0.10, 0.00, window=0, period=0, video]
E/ExoPlayerImplInternal( 2387): Stop failed.
E/ExoPlayerImplInternal( 2387): java.lang.IllegalStateException
E/ExoPlayerImplInternal( 2387): 	at android.media.MediaCodec.native_stop(Native Method)
E/ExoPlayerImplInternal( 2387): 	at android.media.MediaCodec.stop(MediaCodec.java:628)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:518)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:474)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:362)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:972)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:768)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:731)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:353)
E/ExoPlayerImplInternal( 2387): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2387): 	at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal( 2387): 	at android.os.HandlerThread.run(HandlerThread.java:61)
D/EventLogger( 2387): decoderDisabled [0.10, 0.00, window=0, period=0, audio]
D/EventLogger( 2387): mediaPeriodReleased [0.10, 0.00, window=0, period=0]
E/EventLogger( 2387): playerFailed [0.10, 0.00, window=0]
E/EventLogger( 2387): com.google.android.exoplayer2.ExoPlaybackException
E/EventLogger( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
E/EventLogger( 2387): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/EventLogger( 2387): 	at android.os.Looper.loop(Looper.java:135)
E/EventLogger( 2387): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/EventLogger( 2387): Caused by: java.lang.IllegalStateException
E/EventLogger( 2387): 	at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
E/EventLogger( 2387): 	at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
E/EventLogger( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:637)
E/EventLogger( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
E/EventLogger( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
E/EventLogger( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
E/EventLogger( 2387): 	... 3 more
I/NEXX    ( 2387): release
I/ExoPlayerImpl( 2387): Release 17da4922 [ExoPlayerLib/2.8.1] [generic_x86, sdk_google_atv_x86, unknown, 22] [goog.exo.core, goog.exo.ui, goog.exo.mediasession, goog.exo.leanback, goog.exo.dash]
D/EventLogger( 2387): end [0.09]
I/NEXX    ( 2387): release
D/InitFlash( 2387): submit
D/InitFlashAsyncTask( 2387): Constructor
D/SerialReqAsyncTask( 2387): response code: 201
D/SerialReqAsyncTask( 2387): response code: 201
D/APIManager( 2387): Received client token: V741XHKTQAPQCSPNRCJTZ
D/InitFlashAsyncTask( 2387): ---there--- 140
D/SerialReqAsyncTask( 2387): response code: 201
I/NEXX    ( 2387): got client data, play mode is single
D/NEXX    ( 2387): player skin: minimalwithtime
D/NEXX-UI ( 2387): setLayout 2130968694
D/NEXX-UI ( 2387): initControllerView
I/NEXX    ( 2387): got media data, 1 items
D/SerialReqAsyncTask( 2387): response code: 201
I/NEXX    ( 2387): got exit play data, 10 items
D/NEXX    ( 2387): exit play media list available, size 10
D/SerialReqAsyncTask( 2387): response code: 201
I/NEXX    ( 2387): release
D/NEXX    ( 2387): playing media https://funk-01.akamaized.net/c3583d1f-a2ef-4c71-ba17-77d0b144fa80/133618_src.ism/Manifest(format=mpd-time-csf)
I/NEXX    ( 2387): prepare https://funk-01.akamaized.net/c3583d1f-a2ef-4c71-ba17-77d0b144fa80/133618_src.ism/Manifest(format=mpd-time-csf), start position 0
I/ExoPlayerImpl( 2387): Init 21e057fd [ExoPlayerLib/2.8.1] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/EventLogger( 2387): seekStarted [0.00, 0.00, window=0]
D/EventLogger( 2387): positionDiscontinuity [0.00, 0.00, window=0, SEEK]
W/MediaSessionCompat( 2387): Couldn't find a unique registered media button receiver in the given context.
D/EventLogger( 2387): start [0]
D/EventLogger( 2387): state [0.01, 0.00, window=0, false, BUFFERING]
D/ExoPlayerAdapter( 2387): State is buffering
I/NEXX    ( 2387): play
D/EventLogger( 2387): state [0.02, 0.00, window=0, true, BUFFERING]
D/ExoPlayerAdapter( 2387): State is buffering
D/EventLogger( 2387): state [0.02, 0.00, window=0, false, BUFFERING]
D/ExoPlayerAdapter( 2387): State is buffering
D/EventLogger( 2387): positionDiscontinuity [0.02, 0.00, window=0, SEEK]
D/EventLogger( 2387): state [0.03, 0.00, window=0, true, BUFFERING]
D/ExoPlayerAdapter( 2387): State is buffering
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.640028, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.640028, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001F, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001F, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64000D, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.640028, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.640028, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001F, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001F, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64001E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 2387): NoSupport [codec.profileLevel, avc1.64000D, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/EventLogger( 2387): timelineChanged [0.06, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
D/EventLogger( 2387):   period [312.21]
D/EventLogger( 2387):   window [312.16, true, false]
D/EventLogger( 2387): ]
D/EventLogger( 2387): seekProcessed [0.06, 0.00, window=0]
D/EventLogger( 2387): mediaPeriodCreated [0.06, 0.00, window=0, period=0]
D/EventLogger( 2387): loading [0.06, 0.00, window=0, period=0, true]
D/EventLogger( 2387): decoderEnabled [0.06, 0.00, window=0, period=0, video]
D/EventLogger( 2387): decoderEnabled [0.06, 0.00, window=0, period=0, audio]
D/EventLogger( 2387): tracksChanged [0.06, 0.00, window=0, period=0,
D/EventLogger( 2387):   Renderer:0 [
D/EventLogger( 2387):     Group:0, adaptive_supported=YES [
D/EventLogger( 2387):       [ ] Track:0, id=1_V_video_1, mimeType=video/avc, bitrate=5597728, res=1920x1080, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [ ] Track:1, id=1_V_video_2, mimeType=video/avc, bitrate=3720874, res=1920x1080, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [ ] Track:2, id=1_V_video_3, mimeType=video/avc, bitrate=2320375, res=1280x720, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [ ] Track:3, id=1_V_video_4, mimeType=video/avc, bitrate=1397555, res=960x540, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [ ] Track:4, id=1_V_video_5, mimeType=video/avc, bitrate=838895, res=720x404, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [ ] Track:5, id=1_V_video_6, mimeType=video/avc, bitrate=607509, res=640x360, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):       [X] Track:6, id=1_V_video_7, mimeType=video/avc, bitrate=372726, res=320x180, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger( 2387):     ]
D/EventLogger( 2387):   ]
D/EventLogger( 2387):   Renderer:1 [
D/EventLogger( 2387):     Group:0, adaptive_supported=N/A [
D/EventLogger( 2387):       [X] Track:0, id=5_A_aac_UND_2_127_1, mimeType=audio/mp4a-latm, bitrate=127999, sample_rate=48000, supported=YES
D/EventLogger( 2387):     ]
D/EventLogger( 2387):   ]
D/EventLogger( 2387): ]
D/ExoPlayerAdapter( 2387): onTracksChanged
D/EventLogger( 2387): mediaPeriodReadingStarted [0.06, 0.00, window=0, period=0]
I/OMXClient( 2387): Using client-side OMX mux.
W/OMXNodeInstance( 2387): [1:google.h264.decoder] component does not support metadata mode; using fallback
E/ACodec  ( 2387): [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
E/SoftAVC ( 2387): Decoder failed: -2
E/ACodec  ( 2387): [OMX.google.h264.decoder] ERROR(0x80001001)
E/ACodec  ( 2387): signalError(omxError 0x80001001, internalError -2147483648)
E/MediaCodec( 2387): Codec reported err 0x80001001, actionCode 0, while in state 6
E/ExoPlayerImplInternal( 2387): Internal runtime error.
E/ExoPlayerImplInternal( 2387): java.lang.IllegalStateException
E/ExoPlayerImplInternal( 2387): 	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
E/ExoPlayerImplInternal( 2387): 	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:831)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:764)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
E/ExoPlayerImplInternal( 2387): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2387): 	at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal( 2387): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 2387): Stop failed.
E/ExoPlayerImplInternal( 2387): java.lang.IllegalStateException
E/ExoPlayerImplInternal( 2387): 	at android.media.MediaCodec.native_stop(Native Method)
E/ExoPlayerImplInternal( 2387): 	at android.media.MediaCodec.stop(MediaCodec.java:628)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:518)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:474)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:362)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:972)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:768)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:731)
E/ExoPlayerImplInternal( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:353)
E/ExoPlayerImplInternal( 2387): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2387): 	at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal( 2387): 	at android.os.HandlerThread.run(HandlerThread.java:61)
D/EventLogger( 2387): decoderInitialized [0.09, 0.00, window=0, period=0, video, OMX.google.h264.decoder]
D/EventLogger( 2387): decoderInputFormatChanged [0.09, 0.00, window=0, period=0, video, id=1_V_video_7, mimeType=video/avc, bitrate=372726, res=320x180]
D/EventLogger( 2387): downstreamFormatChanged [0.09, 0.00, window=0, period=0, id=1_V_video_7, mimeType=video/avc, bitrate=372726, res=320x180]
D/EventLogger( 2387): decoderDisabled [0.09, 0.00, window=0, period=0, video]
D/EventLogger( 2387): decoderDisabled [0.09, 0.00, window=0, period=0, audio]
D/EventLogger( 2387): mediaPeriodReleased [0.09, 0.00, window=0, period=0]
E/EventLogger( 2387): playerFailed [0.09, 0.00, window=0]
E/EventLogger( 2387): com.google.android.exoplayer2.ExoPlaybackException
E/EventLogger( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
E/EventLogger( 2387): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/EventLogger( 2387): 	at android.os.Looper.loop(Looper.java:135)
E/EventLogger( 2387): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/EventLogger( 2387): Caused by: java.lang.IllegalStateException
E/EventLogger( 2387): 	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
E/EventLogger( 2387): 	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:831)
E/EventLogger( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:764)
E/EventLogger( 2387): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
E/EventLogger( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
E/EventLogger( 2387): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
E/EventLogger( 2387): 	... 3 more
I/NEXX    ( 2387): release
I/ExoPlayerImpl( 2387): Release 21e057fd [ExoPlayerLib/2.8.1] [generic_x86, sdk_google_atv_x86, unknown, 22] [goog.exo.core, goog.exo.ui, goog.exo.mediasession, goog.exo.leanback, goog.exo.dash]
D/EventLogger( 2387): end [0.08]
D/tv.nexx.android.player.reporting.ReportingSystem( 2387): no reporting ID yet, buffering
D/NEXX    ( 2387): UI Error View
D/SerialReqAsyncTask( 2387): response code: 201

</details>

**Comment by stigi** [comment]
@mfentross Any feedback on that issue? We are currently planning to role out our app to API level 22, but (obviously) can't because the player isn't supported. Is this by design? And if so could you provide us with better documentation on API level compatibility? We currently have absolutely no way of telling which platforms we can support.

**Comment by mfentross** [comment]
Hi @stigi , this is an issue in the emulator only. The emulator with old Android versions lacks several codecs that are installed by the vendors on real devices.

**Comment by stigi** [comment]
Thanks for clarifying @mfentross
