### ISSUE TITLE
No way to get the numerical runtime

### ISSUE THREAD

**Issue by stigi** [nexxtv/nexxPLAY-android#14]
I'm trying to calculate the current playback progress in percentage, but the duration returned by the player seems incorrect. I'm actually not sure what value `currentDuration` holds. The `runtime` string looks correct though, but I don't want to go down the route of parsing it...

Here's a snapshot where I'd expect `currentDuration` to be around `166` but got `26`:
```
nexxPlayer.currentTime = 109.004
nexxPlayer.enhancedMediaData.currentTime = 109.004
nexxPlayer.enhancedMediaData.currentDuration = 26.0
nexxPlayer.enhancedMediaData.runtime = "00:02:46"
```

**Comment by boredom2** [comment]
Hi there :)

this is actually correct.
"runtime" gives you the "runtime" or "total duration" of a Video.
"currentTime" gives you the current Playback Position of the Video
"currentDuration" gives yout current Amount of Seconds, that this Video has been watched.

In other Words - these are 3 different Values, and it depends on what you need :)

**Comment by stigi** [comment]
Makes sense somehow. The documentation only contains an entry for `getCurrentTime` and I assumed `currentDuration` to be it's counterpart.

What I need is a way to get the *total duration* without parsing the `runtime` string.

**Comment by boredom2** [comment]
Thats currently not available on no Platform - but I guess, parsing that String is not that hard :)

**Comment by stigi** [comment]
@mfentross Any official feedback on this?

**Comment by boredom2** [comment]
Hello again - for now, we will not change the current Functionality, as we would have to change it on all Platforms vor Consistency. As no other User seems to need this Format, we have currently no Plans to provider a Helper Function for that, but may offer one in a later Version.
For now, this is not planned.
