### ISSUE TITLE
startPosition on startPlay not respected

### ISSUE THREAD

**Issue by stigi** [nexxtv/nexxPLAY-android#18]
Hi,

Sorry, me again ✌️ 

I'm currently implementing a 'recently watched' feature, where we want to start the playback of a video at a stored time.

Passing `startPosition` with `startPlay` unfortunately has no effect though, so we're blocked on that feature. I assume the value is in seconds, right? The documentation doesn't really mention it.

It should be easy to repo by just passing `10` to jump 10 second into the video. That's how I tried it.

Currently running version `3.2.2` of the library.

**Comment by boredom2** [comment]
Hi there,

this sounds like a Bug fore sure.
Besides that, what @mfentross will take a look at - it is not necessary, that you create a "local History" of Play Positions yourself, as the Player creates that anyway (currently for Recommendation Purposes).
As this Topic comes up more and more often, we are evaluating the Exposal of these Data more easily and adding a Parameter for "always continue were last stopped".
We do this already for "real" Users (with a User ID on our Systems), synchronized over all Platforms, but not yet for "anonymous" Users on a single Device.
Would this be something, you would be interested in?

Thanks!

**Comment by stigi** [comment]
@boredom2 We weren't aware that you're storing user related data on your backend.

But leaving that aside, this is a feature we want to own in our app. i.E. we want to show a list of recently played items and overlay them with a progress indicator.

The documentation implied that such a feature would be feasible to implement, but from looking at the decompiled version of your lib it looks like the `startPosition` parameter is only passed down to the call of `PlayerLogic.startPlay` from where on it's not used any further.

I tried working around the issue by using `swapPos` which is also mentioned in the documentation (and frankly a basic feature every player should support), but ran into #20.

Quite frustrating, tbh

**Comment by mfentross** [comment]
Hi @stigi ,

the problem with the ignored startPosition has been fixed in v 3.2.20
