### ISSUE TITLE
Mute button does not work in followup-videos

### ISSUE THREAD

**Issue by ebonhart** [nexxtv/nexxPLAY-android#21]
The button to mute/unmute the sound does only work while the first video is being played. For any subsequent video play or replay of the first video, the button doesn't react anymore.

This is a very old bug. My latest information was that this would be fixed in the upcoming version 3.x of the nexx player sdk. Today, I updated from version 2.1.1 to version 3.2.18 of the SDK and the issue is still not fixed. Therefore I am filing this issue again.

**Comment by mfentross** [comment]
Hi @ebonhart,

there still was a fix in the UI handling, so thank you for reporting! It is fixed in 3.2.20 now
