### ISSUE TITLE
TV - Video controls immediately lose focus 

### ISSUE THREAD

**Issue by AndreaLoden** [nexxtv/nexxPLAY-android#27]
Hi @mfentross ,

we have two issues with the player:

1-  Expected behaviour: while playing a video click on central button on remote( or enter on emulator), video is paused and video controls appear

Actual behaviour: nothing happens

Cause: I think the video controls lose focus when the image is loaded, or just before that

2-Expected behaviour: some button that is not play/pause is focused -> controls are hidden after timeout-> click on central button on remote( or enter on emulator), video is paused/resumed

Actual behaviour: the previous button is still focused and the related action is executed (for example fast forward)

We followed instructions on how to use the player. You can check out our sample project, you should have access

Here is a video that maybe explains better what I mean https://www.youtube.com/watch?v=Jm8sG_805zE

**Comment by mfentross** [comment]
Hi @AndreaLoden ,

thank you for reporting and the screen cast! I am looking into the issue.

**Comment by NetPumi2** [comment]
+1
Hi we have similar problem on android. When i am moving on progress bar all control buttons disappear and i have no way how to control video

**Comment by mfentross** [comment]
Hi @AndreaLoden , this has been implemented in v.3.2.46.

@NetPumi2 This is not related to your issue. Could you please open another ticket and describe your problem in detail?
