### ISSUE TITLE
Question: Oldest android version supported by nexx 3.2.x?

### ISSUE THREAD

**Issue by fdobre** [nexxtv/nexxPLAY-android#31]
Some users have reported crashes on older android versions, we noticed the player crashes on android 4.2.

@boredom2 what is the oldest android version supported by Nexx player 3.2.x?

Is is possible to have this info in the readme file for both Android and IOS?

Thanks a lot in advance!

**Comment by boredom2** [comment]
We only support 4.4 and up on all Versions (also Web). This is handled on a contractual Level (and the Information is available in the general Player Docs). 
In 2019 we will probably skip Support for 4.4 also.

**Comment by fdobre** [comment]
@boredom2 OK, thank you for the fast response!
