### ISSUE TITLE
Player crashes with `tv.nexx.android.player.omnia.VideoUrlBuilderVod.buildFree` error

### ISSUE THREAD

**Issue by fdobre** [nexxtv/nexxPLAY-android#35]
VideoUrlBuilderVod.java line 72
tv.nexx.android.player.omnia.VideoUrlBuilderVod.buildFree

**Comment by fdobre** [comment]
Version 3.2.43

![screen shot 2019-01-10 at 5 01 52 pm](https://user-images.githubusercontent.com/3833179/50977674-71cb3380-14fb-11e9-9f84-563d81bc4c39.png)

**Comment by fdobre** [comment]
![screen shot 2019-01-10 at 5 17 30 pm](https://user-images.githubusercontent.com/3833179/50977775-a6d78600-14fb-11e9-90ff-e0ae493bebc7.png)

**Comment by mfentross** [comment]
Hi @fdobre ,

thank you for your patience. This issue has been fixed in the update v.3.3.0
