### ISSUE TITLE
Seek is not working

### ISSUE THREAD

**Issue by atiqmumtaz507** [nexxtv/nexxPLAY-android#51]
I am using NEXX SDK in an Android App and player does not have UI. Item is played but there are 2 issues
- Time Duration is wrong
- Seek is not working at all

Item which the SDK plays has this 3qId "86aa89e8-d1f8-48ce-b5c8-cc07e0792a31" 

{streamtype=audio, data={playbackSpeed=1.0, duration=5, isPreview=0, fullDuration=0.001, isBumper=0, isStory=0, isSceneSplit=0, time=4.525, isPresentation=0, isMuted=0}, global_id=2378518, mediaIndex=0, remoteDevice=, event=second, mediaID=1130301, playerMode=audio, playerIndex=0, playerContainer=}

The real time what I see in the Notification is 05:55 of the played article. Why the Duration is 0.001?

Seek Method "nexxPlay.seekTo(20)" is not working as well. 

I guess this returns false
public boolean canSeekForward() {
            return exoPlayer.getDuration() > exoPlayer.getCurrentPosition();
        }
        
        @boredom2 Please help !!

**Comment by atiqmumtaz507** [comment]
@neko-fire @mfentross

**Comment by boredom2** [comment]
I suppose you are working for the NOZ Apps. We are aware that these Apps use a highly outdated SDK Version (and additionally, a RC Version, which was never officially released).
Furthermore - I dont think we should discuss internal Ids in a publically available Ticket :)
Lets stick to the official Workflow and maybe we can setup a meeting between the Devs here.

**Comment by atiqmumtaz507** [comment]
@boredom2 Yes it is a NOZ App. I tested the above seek method with the latest SDK Release "tv.nexx.android:play:6.3.10"

**Comment by boredom2** [comment]
Okay, that sounds indeed interesting. I will give this to the dev group and update you when I get an update.
Still, lets keep the official communication channels next time please 😉

**Comment by boredom2** [comment]
Hi there, we can confirm this and will provide a Fix.
I noticed various other Tickets from you, which for some reasons I never got informed upon. And the amount of information does not seem to be sufficient to replicate.

Still, if there is any other Bug you can replicate and provide us with testing data, we are happy to look into it before we compile a new release.
