### ISSUE TITLE
Prev/Next button on remote do nothing in leanback mode

### ISSUE THREAD

**Issue by toto** [nexxtv/nexxPLAY-android#7]
When using the SDK in leanback mode the prev/next buttons on the remote do nothing. They should behave same as the onscreen buttons. Note that this is required for Amazon certification

## To Reproduce: 

1. Play a video in leanback mode
2. Press "Next" on the remote

## Expected: 

Same as selecting the next button in leanback UI and pressing "enter" (skip ~10secs)

## Actual

Nothing happens

Tested on 

- Fire OS 5.2.6.3
- Android TV Emulator (Android 8)

**Comment by mfentross** [comment]
Hi @toto ,

thanks for your post. Could you please check again with v 3.1.8?

And also please regard the requirement for Android TV (onKeyEvent) in your Player Activity as described in [the corresponding section](https://github.com/nexxtv/nexxPLAY-android#android-tv)
