### ISSUE TITLE
Migrating from version 1 to version 3

### ISSUE THREAD

**Issue by fdobre** [nexxtv/nexxPLAY-android#9]
Hi,

I was able to make the version 3 build and play movies by fixing some breaking changes created by removing the method setVideoFrameAndSurfaceView and renaming the events constants.

The last issue we are having is extracting info from the mediaData object which seems to have changed:

```
         MediaData mediaData = player.getMediaData();
         String label = null;
         if (mediaData != null) {
            // code crashes here because getId and getTitle methods are missing
            label = mediaData.getId() + ":" + mediaData.getTitle();
          }

        // ..... code here which uses label to submit some analytics info
```

We need your advice what to use to extract the mediaData info

**Comment by fdobre** [comment]
I was able to fix the mediaData.getId() issue by replacing that with the new method from there.

Including the library as compile 'tv.nexx:nexxplay-android:3.+' works but including latest version 
 like 'tv.nexx:nexxplay-android:3.0.5' doesn't build because of some inconsistencies in player event names.....

How can we include latest version without '3.+' 

Can you help us and add new release tags in git?

As a small note: old event names like START_PLAYBACK were a bit more intuitive and easy to read but we are happy the readme file has been updated. Thank you for updating it!

**Comment by fdobre** [comment]
Upgrade from v1 to v3 was successful, closing this ticket.

**Comment by boredom2** [comment]
Thats great, thank you.
